### PR TITLE
Adding new fields to datasource's plugin tab

### PR DESCRIPTION
**Pull request by sengineer0**
Depends on: https://github.com/newgene/biothings.api/pull/63

ref: https://github.com/biothings/biothings_studio/issues/106

### CODE REVIEW

**Comment by newgene** [comment]
@sengineer0 another merging conflict to fix here. Thanks!

**Comment by sengineer0** [comment]
> @sengineer0 another merging conflict to fix here. Thanks!

@newgene  no problem. the conflict is resolved now.

**Comment by newgene** [comment]
@sengineer0 please describe the expected UI behavior of this PR.

**Comment by sengineer0** [comment]
@newgene 

Regarding to this PR: https://github.com/newgene/biothings.api/pull/63, 2 new fields will be added to the plugin's manifest file: `display_name`, `biothing_type`.

In order to support that change, this PR will display these fields in the Source's plugin page using labels: `Name` and `Biothing Type`

Beside of that, the `biothing_type` comes from manifest file, will be used as default doc_type value in `quick_index` feature. Or to provide information about what default `doc_types` are available, and each `doc_type` comes from how many data sources.

Please check my attached screenshots for details


Selection_014
Selection_015
Selection_016

**Pull request merged**
