### PR TITLE
Implement quick search feature

### PR DESCRIPTION
**Pull request by sengineer0**
https://github.com/biothings/biothings_studio/issues/104

### CODE REVIEW

**Comment by newgene** [comment]
@sengineer0 fyi, there are some conflicts after I merged a few other PRs.

**Comment by sengineer0** [comment]
> @sengineer0 fyi, there are some conflicts after I merged a few other PRs.

@newgene  The conflicts are resolved.

**Comment by newgene** [comment]
@sengineer0 For future reference, please add a description of the expected behavior from this new feature

**Comment by newgene** [comment]
This new feature works very nicely!

A few minor notes:
* Add a message in quick_search modal about the `ctrl-shirt-p` shortcut.
* Can the highlighting in the matching list table, currently grey, be more obvious, maybe other color?

**Comment by sengineer0** [comment]
> This new feature works very nicely!
> 
> A few minor notes:
> 
> * Add a message in quick_search modal about the `ctrl-shirt-p` shortcut.
> * Can the highlighting in the matching list table, currently grey, be more obvious, maybe other color?

sure. let's me update.

**Comment by sengineer0** [comment]
> @sengineer0 For future reference, please add a description of the expected behavior from this new feature

@newgene 

- The quick search feature will allow user to type a string, and search for any datasource, build, release, api, which has name contains the query string
- the feature can be triggered by
  -  clicking on the `Search` button in the nav bar, beside the `Edit Studio Configuration` button
  -  pressing `Ctrl + Shift + P`, like the VS Code does.
Selection_002

- the content used for searching is fetched first time when the site is loaded, and every 5 minutes later. The user can manually refresh the content by click on a button beside the search input.
Selection_001

**Comment by sengineer0** [comment]
> Add a message in quick_search modal about the ctrl-shirt-p shortcut.

@newgene 
can you tell me the message you want to add to quick search modal, should be ?
I don't know what purpose of it.

**Comment by newgene** [comment]
@sengineer0 just like this to remind users about the keyboard shortcut:

image

**Comment by newgene** [comment]
@sengineer0 and just to polish it a bit more, let's add an icon for "refresh cache" button, and leave some space between the search box and the button.

**Comment by sengineer0** [comment]
@newgene it's clear now. I am updating the code now

**Comment by newgene** [comment]
@sengineer0 new enhancement looks good to me.

One quick thing to check with you, is "Cmd-Shift-P" on Mac equivalent of "Ctrl-Shift-P" on Windows or Linux instead (e.g. on vscode)? If so, we want to keep consistent with this behavior, including the tip text.

**Comment by newgene** [comment]
@sengineer0 another feedback from our team members earlier today:

* Can you add a tool tip to "refresh cache" explain what it does, and how it's updated otherwise?

**Comment by sengineer0** [comment]
> Can you add a tool tip to "refresh cache" explain what it does, and how it's updated otherwise?

@newgene  sure, I will add it.

**Comment by sengineer0** [comment]
> @sengineer0 new enhancement looks good to me.
> 
> One quick thing to check with you, is "Cmd-Shift-P" on Mac equivalent of "Ctrl-Shift-P" on Windows or Linux instead (e.g. on vscode)? If so, we want to keep consistent with this behavior, including the tip text.

I tested in a mac laptop. the `Ctrl-Shift-P`  can work as expect.
Do you want to change to `Cmd-Shift-P` in Mac, or keep use `Ctrl-Shift-P` for consistency.

@newgene

**Comment by newgene** [comment]
Let's do `Cmd-Shift-P` on Mac to be consistent with vscode.

How about Firefox behavior? That could impact this decision too.

@sengineer0

**Comment by sengineer0** [comment]
this shortcut `Ctrl-Shift-P`  cannot work with firefox in linux system
but `Cmd-Shift-P` can.

@newgene

**Pull request merged**
