### PR TITLE
Update logviewer to match logic with the backend

### PR DESCRIPTION
**Pull request by sengineer0**
Ref:
https://github.com/biothings/biothings_studio/issues/65
https://github.com/newgene/biothings.api/pull/6

### CODE REVIEW

**Comment by newgene** [comment]
@sengineer0 

image

1. Let's make "View Logs" above the stage tabs, consistent with other tabs (click "view logs" to show log elements, otherwise, just a button). 
2. "View logs by stage:" --> "View logs by stage**s**:", and need some paddings around the text.

**Comment by sengineer0** [comment]
> @sengineer0
> 
> image
> 
> 1. Let's make "View Logs" above the stage tabs, consistent with other tabs (click "view logs" to show log elements, otherwise, just a button).
> 2. "View logs by stage:" --> "View logs by stage**s**:", and need some paddings around the text.

I see, it is quite difficult to do that, as we will change the `LogViewer` to support multiple tab stages.
anyway, I will give it a try

**Comment by sengineer0** [comment]
@newgene  it's updated

the LogViewer for multi stages will look like this:

When hide:
Selection_011

When show:
Selection_012

**Comment by newgene** [comment]
@sengineer0 looks good overall! Two minor improvements:

* remove tabs at the initial view, just show "View Logs" button, consistent with other places
image

* This two "Unavailable" sub-tabs have inconsistent display:

   * DIFF tab:
      
      image

    * SYNC tab:
       
       image

     Probably should add the same msg to the "DIFF" sub-tab

**Comment by sengineer0** [comment]
> @sengineer0 looks good overall! Two minor improvements:
> 
> * remove tabs at the initial view, just show "View Logs" button, consistent with other places
> 
> image
> 
> * This two "Unavailable" sub-tabs have inconsistent display:
>   
>   * DIFF tab:
>      image
>   * SYNC tab:
>      image
>   
>   Probably should add the same msg to the "DIFF" sub-tab

It's fixed now.

**Comment by newgene** [comment]
@sengineer0 Another minor thing I noticed, the log file dropdown at SNAPSHOT tab seems not consistent with other tabs. The file path in other tabs usually has `build/<build_name>/*.log`, but SNAPSHOT log dropdown has only the logfile names. 

image

v.s. 

image

**Comment by newgene** [comment]
@sengineer0 because studio is based on element UI library, can we just use its tab style from this library?

Like these examples: https://element.eleme.cn/2.3/#/en-US/component/tabs  (Studio uses v2.3.x currently)

The current tab styles looks like just some plain jquery tabs, works just does not look consistent/polished comparing to the rest of the site.

For example, this basic tab style seems good enough (also different from the tab style of the main tabs):
image

**Comment by sengineer0** [comment]
> @sengineer0 Another minor thing I noticed, the log file dropdown at SNAPSHOT tab seems not consistent with other tabs. The file path in other tabs usually has `build/<build_name>/*.log`, but SNAPSHOT log dropdown has only the logfile names.
> 
> image
> 
> v.s.
> 
> image

It's fixed.
but it required a change in the biothings.api, I created a PR for it. please have a look: https://github.com/newgene/biothings.api/pull/17

**Comment by sengineer0** [comment]
> @sengineer0 because studio is based on element UI library, can we just use its tab style from this library?
> 
> Like these examples: https://element.eleme.cn/2.3/#/en-US/component/tabs (Studio uses v2.3.x currently)
> 
> The current tab styles looks like just some plain jquery tabs, works just does not look consistent/polished comparing to the rest of the site.
> 
> For example, this basic tab style seems good enough (also different from the tab style of the main tabs): image

let's me check it

**Comment by sengineer0** [comment]
> @sengineer0 because studio is based on element UI library, can we just use its tab style from this library?
> 
> Like these examples: https://element.eleme.cn/2.3/#/en-US/component/tabs (Studio uses v2.3.x currently)
> 
> The current tab styles looks like just some plain jquery tabs, works just does not look consistent/polished comparing to the rest of the site.
> 
> For example, this basic tab style seems good enough (also different from the tab style of the main tabs): image

@newgene  I checked that Biothings Studio doesn't use element UI library anywhere.
The stage logs was created like the tab in top of the Build page.
If you really want to use Element UI, I will try to replace with that library.

Selection_005

**Comment by newgene** [comment]
ah, my mistake! It should be semantic UI, not element UI. The possible tab styles are here:

https://semantic-ui-vue.github.io/#/modules/tab

**Comment by sengineer0** [comment]
`semantic-ui-vue` is actually a third party package. I tried to use it, but it not easy to port the current stage log to use that package.
Because we are currently use plain `semantic-ui`, so I think we can simplly change a little bit the stage logs, and it will look like other tabs: for example: action tabs in Source view

Selection_007
=> Source view's tabs

Selection_008
=> After I update the stage logs tabs

**Comment by newgene** [comment]
@sengineer0 new tab style looks great!

* Full screen view of the log dialog by clicking the square icon on the top-right needs to have a scrollbar when the logs displays longer than the screen height (screenshot below)

* Can you please verify the log lines retrieved from the /log endpoint will be capped (e.g. 1000 lines max), so that we won't load a super big log file to crash the browser? We should have implemented it on the backend, but let's check to be sure, and maybe add a text like "logs were capped at 1000 lines" to the UI if the log lines hit its max.

* Let's change the log font to a mono font, maybe reduce the linespace as well. Just to make it display like from a linux console.
  This could be a good option: https://fonts.google.com/specimen/JetBrains+Mono (or you can pick your favorite one for your terminal or IDE)


This is the screenshot of a full screen view:
image

**Comment by newgene** [comment]
FYI. I created a separate issue for the last mono-font request: https://github.com/biothings/biothings_studio/issues/89, (the style changes are applicable for both trackback and logs dialogs)

**Comment by sengineer0** [comment]
@newgene 

>Full screen view of the log dialog by clicking the square icon on the top-right needs to have a scrollbar when the logs displays longer than the screen height (screenshot below)

=> sure I will add it


>Can you please verify the log lines retrieved from the /log endpoint will be capped (e.g. 1000 lines max), so that we won't load a super big log file to crash the browser? We should have implemented it on the backend, but let's check to be sure, and maybe add a text like "logs were capped at 1000 lines" to the UI if the log lines hit its max.

=> Currently we let the studio download the log file, and display it to user
If we want to show only a limit lines, there are 2 options:
- Option 1: we will handle it on backend, it will be better because, it reduces the download time. but it requires more time to implement.
- Option 2: if the download time is not a problem with our users, we can simple let the studio decide how to display the log's content.

>Let's change the log font to a mono font, maybe reduce the linespace as well. Just to make it display like from a linux console.
This could be a good option: https://fonts.google.com/specimen/JetBrains+Mono (or you can pick your favorite one for your terminal or IDE)

=> ok I will check it later

**Comment by newgene** [comment]
>Option 1: we will handle it on backend, it will be better because, it reduces the download time. but it requires more time to implement.

@sengineer0 Very likely we already had this feature (like passing a lineno parameter with a default value) in-place when we implemented the log handler, can you please confirm? Agree that we should do it at the backend.

**Comment by newgene** [comment]
@sengineer0 yeah, I had a look at the code, we did implement a `lines` parameter here:

https://github.com/biothings/biothings.api/blob/a0d498c818ba47409485c4986b87813a16ec9c8c/biothings/hub/api/handlers/log.py#L86-L103

So just need to make sure studio UI uses this parameter to cap the number of lines, and when the output lines equal to the cap, display a text of "the log lines are likely truncated at max # lines". No need to display it when the lines are less than the cap.

We can start with the line no cap at 1000 for now, can be adjusted if needed.

**Comment by sengineer0** [comment]
ok I see that. Let's me try to implement "capped lines" feature.

**Comment by sengineer0** [comment]
>Full screen view of the log dialog by clicking the square icon on the top-right needs to have a scrollbar when the logs displays longer than the screen height (screenshot below)

>Can you please verify the log lines retrieved from the /log endpoint will be capped (e.g. 1000 lines max), so that we won't load a super big log file to crash the browser? We should have implemented it on the backend, but let's check to be sure, and maybe add a text like "logs were capped at 1000 lines" to the UI if the log lines hit its max.

These issues was resolved.
Regarding to the max cap of log lines, I created a PR in biothings.api to change how the BE processes the log, before sends it back to UI.
Please check it too. https://github.com/newgene/biothings.api/pull/18

**Pull request merged**
